"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import StatCard from "@/components/dashboard/StatCard";
import ResultsChart from "@/components/dashboard/ResultsChart";
import AccuracyTrend from "@/components/dashboard/AccuracyTrend";
import RecentGames from "@/components/dashboard/RecentGames";
import { ErrorState, LoadingState } from "@/components/ui/AsyncState";
import { ApiError, fetchJson } from "@/lib/api/fetch-json";
import AppShell from "@/components/layout/AppShell";

type DashboardData={username:string;stats:{gamesImported:number;gamesAnalyzed:number;winRate:number;drawRate:number;averageAccuracy:number;averageACPL:number;blundersPerGame:number};resultSeries:{result:"win"|"loss"|"draw";date:string}[];accuracyTrend:{date:string;accuracy:number}[];recentGames:{id:string;date:string;opponent:string;color:"White"|"Black";result:"Win"|"Loss"|"Draw";accuracy:number|null;timeControl:string;analysisStatus:string}[]};
type AnalysisProfile="quick"|"standard"|"deep";
type WorkerHealth={worker?:{configured?:boolean;alive?:boolean;state?:string;error?:string}};
type AnalysisJob={id:string;status:"QUEUED"|"RUNNING"|"COMPLETED"|"FAILED"|"CANCELLED";profile:string;depth:number;requested:number;completed:number;failed:number;remaining:number;currentGameId:string|null;cancelRequested:boolean;lastError:string|null};

export default function DashboardClient({username}:{username:string}){
 const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState<string|null>(null),[stage,setStage]=useState(""),[notice,setNotice]=useState<string|null>(null);
 const fetchDashboard=useCallback(()=>fetchJson<DashboardData>(`/api/players/${encodeURIComponent(username)}/dashboard`,{cache:"no-store"}),[username]);
 const sync=useCallback(async()=>{setStage("Fetching your public Chess.com games…");const b=await fetchJson<{imported:number}>(`/api/players/${encodeURIComponent(username)}/sync`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({maxGames:50})});setStage(`Imported ${b.imported} new games. Preparing dashboard…`);},[username]);
 const load=useCallback(async()=>{setError(null);setData(null);try{setStage("Loading player data…");setData(await fetchDashboard());setStage("");}catch(err){if(err instanceof ApiError&&err.code==="PLAYER_NOT_IMPORTED"){try{await sync();setData(await fetchDashboard());setStage("");}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard");setStage("");}}else{setError(err instanceof Error?err.message:"Unable to load dashboard");setStage("");}}},[fetchDashboard,sync]);
 useEffect(()=>{load();},[load]);
 const [job,setJob]=useState<AnalysisJob|null>(null),[profile,setProfile]=useState<AnalysisProfile>("quick"),[workerHealth,setWorkerHealth]=useState<WorkerHealth|null>(null);
 const pollJob=useCallback(async()=>{const result=await fetchJson<{job:AnalysisJob|null}>(`/api/players/${encodeURIComponent(username)}/analysis-queue`,{cache:"no-store"});setJob(result.job);return result.job;},[username]);
 useEffect(()=>{let timer:ReturnType<typeof setInterval>|null=null;let active=true;pollJob().catch(()=>undefined).finally(()=>{timer=setInterval(()=>{if(active)pollJob().catch(()=>undefined);},2000);});return()=>{active=false;if(timer)clearInterval(timer);};},[pollJob]);
 const pollWorker=useCallback(async()=>{try{setWorkerHealth(await fetchJson<WorkerHealth>("/api/health",{cache:"no-store"}));}catch{setWorkerHealth(null);}},[]);
 useEffect(()=>{pollWorker();const t=setInterval(pollWorker,10000);return()=>clearInterval(t);},[pollWorker]);
 const analyze=async()=>{setError(null);setNotice(null);try{setStage("Creating background analysis job…");const result=await fetchJson<{job:AnalysisJob}>(`/api/players/${encodeURIComponent(username)}/analysis-queue`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile,limit:5})});setJob(result.job);setStage("");if(result.job.requested===0){setNotice("All currently imported games are already analyzed.");}else{setNotice(`Background analysis started for ${result.job.requested} games. You can safely leave this page.`);}}catch(e){setError(e instanceof Error?e.message:"Unable to start analysis");setStage("");}};
 const cancel=async()=>{if(!job)return;try{const result=await fetchJson<{job:AnalysisJob}>(`/api/analysis-jobs/${encodeURIComponent(job.id)}/cancel`,{method:"POST"});setJob(result.job);setNotice("Cancellation requested. The current engine task will finish before the queue stops.");}catch(e){setError(e instanceof Error?e.message:"Unable to cancel analysis");}};
 if(error&&!data)return <AppShell username={username}><ErrorState title="Could not load this Chess.com profile" message={error} onRetry={load}/></AppShell>;
 if(!data)return <AppShell username={username}><LoadingState title={stage||"Loading player dashboard…"}/></AppShell>;
 const engineReady=data.stats.gamesAnalyzed>0;
 const jobActive=!!job && ["QUEUED","RUNNING"].includes(job.status);
 const progress=job&&job.requested?Math.round(((job.completed+job.failed)/job.requested)*100):0;
 return <AppShell username={data.username}><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
  <header className="flex flex-col justify-between gap-5 border-b border-white/10 pb-6 xl:flex-row xl:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-cyan-300/70">Chesslysis · Real player dashboard</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">{data.username}</h1><p className="mt-2 text-sm text-slate-500">{data.stats.gamesImported} real games imported from Chess.com <span className="mx-1">·</span> {data.stats.gamesAnalyzed} engine-analyzed</p></div><div className="flex flex-wrap items-center gap-2"><select aria-label="Analysis quality" value={profile} onChange={e=>setProfile(e.target.value as AnalysisProfile)} disabled={!!stage||jobActive} className="rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5 text-sm text-slate-200 outline-none"><option value="quick">Quick · depth 10</option><option value="standard">Standard · depth 14</option><option value="deep">Deep · depth 18</option></select><button onClick={analyze} disabled={!!stage||jobActive} className="rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-50">{jobActive?"Analysis running…":"Analyze next 5 games"}</button>{job&&jobActive&&<button onClick={cancel} className="rounded-xl border border-rose-400/30 px-4 py-2.5 text-sm font-semibold text-rose-200 hover:bg-rose-400/10">Cancel</button>}<Link href={`/insights/${encodeURIComponent(username)}`} className="rounded-xl border border-white/15 bg-white/[.02] px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/[.06]">Advanced insights →</Link><Link href={`/performance/${encodeURIComponent(username)}`} className="rounded-xl border border-white/15 bg-white/[.02] px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/[.06]">Performance →</Link></div></header>
  {jobActive&&workerHealth?.worker?.configured===false&&<div className="rounded-xl border border-rose-400/30 bg-rose-400/[.08] px-4 py-3 text-sm text-rose-100">Analysis worker is not configured on the server. Set ANALYSIS_WORKER_TOKEN and ANALYSIS_WORKER_ENABLED=true, then redeploy.</div>}
  {jobActive&&workerHealth?.worker?.configured&&workerHealth.worker.alive===false&&<div className="rounded-xl border border-amber-400/30 bg-amber-400/[.08] px-4 py-3 text-sm text-amber-100">The analysis worker heartbeat is stale. The queue is preserved, but processing needs a server restart or worker recovery. Check /api/health and analysis diagnostics.</div>}
  {(stage||jobActive)&&<div className="rounded-xl border border-cyan-400/20 bg-cyan-400/[.07] px-4 py-3 text-sm text-cyan-100"><div>{stage||`Background analysis: ${job?.status.toLowerCase()}`}</div>{job&&job.requested>0&&<><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-950/60"><div className="h-full rounded-full bg-cyan-400 transition-all" style={{width:`${progress}%`}}/></div><div className="mt-2 text-xs text-cyan-200/70">{job.completed} completed · {job.failed} failed · {job.remaining} remaining · {progress}% · depth {job.depth}</div><div className="mt-1 text-xs text-cyan-200/50">Analysis continues on the server even if you close this page.</div>{job.lastError&&<div className="mt-2 rounded-lg bg-rose-400/10 px-2 py-1 text-xs text-rose-200">Latest worker error: {job.lastError}</div>}</>}</div>}{notice&&<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.07] px-4 py-3 text-sm text-emerald-100">{notice}</div>}{error&&<div className="rounded-xl border border-rose-400/20 bg-rose-400/[.07] px-4 py-3 text-sm text-rose-100">{error}</div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Games imported" value={String(data.stats.gamesImported)}/><StatCard label="Win rate" value={`${data.stats.winRate.toFixed(1)}%`}/><StatCard label="Analyzed" value={String(data.stats.gamesAnalyzed)}/><StatCard label="Average accuracy" value={engineReady?`${data.stats.averageAccuracy.toFixed(1)}%`:"—"} detail={engineReady?undefined:"Run engine analysis"}/><StatCard label="Average ACPL" value={engineReady?data.stats.averageACPL.toFixed(1):"—"} detail={engineReady?undefined:"Run engine analysis"}/></section>
  {!engineReady&&<div className="rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-5 text-sm text-amber-100"><strong>Real games are loaded.</strong> Accuracy and ACPL are intentionally blank until Stockfish finishes. Start a background batch; progress is saved automatically.</div>}
  <section className="grid gap-6 xl:grid-cols-2"><ResultsChart games={data.resultSeries}/><AccuracyTrend points={data.accuracyTrend}/></section><RecentGames games={data.recentGames}/>
 </main></AppShell>;
}
