"use client";
import { useCallback,useEffect,useState } from "react";
import AppShell from "@/components/layout/AppShell";
import { ErrorState,LoadingState,EmptyState } from "@/components/ui/AsyncState";
import { fetchJson } from "@/lib/api/fetch-json";
type Recommendation={id:string;title:string;reason:string;priority:"HIGH"|"MEDIUM"|"LOW";objective:string;drills:string[];evidence:{occurrences:number;gamesAffected:number;averageLoss:number;severity:number}}; type Data={gamesAnalyzed:number;recommendations:Recommendation[]};
export default function TrainingClient({username}:{username:string}){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);try{setData(await fetchJson<Data>(`/api/players/${encodeURIComponent(username)}/training`,{cache:"no-store"}))}catch(e){setError(e instanceof Error?e.message:"Could not load training plan")}},[username]);
 useEffect(()=>{load()},[load]);
 if(error)return <AppShell username={username}><ErrorState title="Could not load training plan" message={error} onRetry={load}/></AppShell>;
 if(!data)return <AppShell username={username}><LoadingState title="Ranking your training priorities..."/></AppShell>;
 return <AppShell username={username}><main className="mx-auto max-w-[1500px] px-4 py-7 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">Phase 2.4 · Training Intelligence</p><h1 className="mt-2 text-3xl font-bold">Personal Training Plan</h1><p className="mt-2 text-sm text-slate-400">Evidence-ranked recommendations from recurring mistakes across {data.gamesAnalyzed} analyzed games.</p>{!data.recommendations.length?<div className="mt-6"><EmptyState title="No urgent training priority" message="Analyze more games to make the recommendations more reliable."/></div>:<div className="mt-7 grid gap-5 xl:grid-cols-2">{data.recommendations.map((r,i)=><section key={r.id} className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs uppercase tracking-wider text-slate-500">Priority #{i+1}</span><h2 className="mt-1 text-xl font-bold">{r.title}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.priority==="HIGH"?"bg-red-400/15 text-red-300":r.priority==="MEDIUM"?"bg-amber-400/15 text-amber-300":"bg-cyan-400/15 text-cyan-300"}`}>{r.priority}</span></div><p className="mt-4 text-sm leading-6 text-slate-400">{r.reason}</p><div className="mt-4 rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="text-xs uppercase tracking-wider text-emerald-300">Training objective</div><p className="mt-2 text-sm text-slate-200">{r.objective}</p></div><div className="mt-4"><div className="text-xs uppercase tracking-wider text-slate-500">Focused drills</div><ol className="mt-2 space-y-2 text-sm text-slate-300">{r.drills.map((d,j)=><li key={d} className="flex gap-3"><span className="font-mono text-cyan-300">0{j+1}</span><span>{d}</span></li>)}</ol></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-white/10 pt-4 text-center"><Metric v={r.evidence.occurrences} l="errors"/><Metric v={r.evidence.gamesAffected} l="games"/><Metric v={r.evidence.severity} l="risk /100"/></div></section>)}</div>}</main></AppShell>
}
function Metric({v,l}:{v:number;l:string}){return <div><div className="font-mono text-lg font-bold text-violet-300">{v}</div><div className="text-[10px] uppercase text-slate-500">{l}</div></div>}
