"use client";
import { useMemo, useState } from "react";
import { Chess } from "chess.js";

type Move={ply:number;moveNumber:number;color:"w"|"b";san:string;fenAfter:string};
type Analysis={evaluationAfter:number|null;bestMove:string|null;principalVariation:string[];evaluationLoss:number;classification:string};
const files=["a","b","c","d","e","f","g","h"];
const glyph:any={wp:"♙",wr:"♖",wn:"♘",wb:"♗",wq:"♕",wk:"♔",bp:"♟",br:"♜",bn:"♞",bb:"♝",bq:"♛",bk:"♚"};
function tone(c?:string){if(!c)return "border-[var(--line)] text-[var(--muted)]"; if(c.includes("BLUNDER"))return "border-[#bd5d52] bg-[#bd5d52] text-white";if(c.includes("MISTAKE"))return "border-[#b97842] text-[#a96f3c]";if(c.includes("INACCURACY"))return "border-[#b89358] text-[#9b773f]";return "border-[var(--accent)] text-[var(--accent)]"}
export default function GameReviewBoard({moves,analyses={}}:{moves:Move[];analyses?:Record<number,Analysis>}){
 const [index,setIndex]=useState(Math.max(-1,moves.length?0:-1));
 const fen=index<0?new Chess().fen():(moves[index]?.fenAfter??new Chess().fen()); const chess=useMemo(()=>{const c=new Chess();try{c.load(fen)}catch{}return c},[fen]); const board=chess.board(); const current=index>=0?moves[index]:undefined; const a=current?analyses[current.ply]:undefined;
 const evals=moves.map(m=>analyses[m.ply]?.evaluationAfter??0); const max=Math.max(2,...evals.map(v=>Math.abs(v)));
 const classification=(a?.classification||"GOOD").toUpperCase(); const before=index>0?(analyses[moves[index-1].ply]?.evaluationAfter??0):0; const after=a?.evaluationAfter??0;
 return <div className="grid min-h-[720px] border-y border-[var(--line)] bg-[var(--surface)] xl:grid-cols-[266px_minmax(460px,1fr)_310px]">
  <aside className="order-2 flex min-h-0 flex-col border-r border-[var(--line)] xl:order-1"><div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-4"><span className="ch-eyebrow text-[8px] text-[var(--muted)]">MOVES</span><span className="ch-mono text-[9px] text-[var(--muted)]">{moves.length} total</span></div><div className="flex-1 overflow-y-auto">{moves.map((m,i)=>{const c=analyses[m.ply]?.classification;return <button key={m.ply} onClick={()=>setIndex(i)} className={`flex w-full items-center gap-3 border-b border-[var(--line)] px-4 py-2.5 text-left text-[12px] ${i===index?"border-l-2 border-l-[var(--accent)] bg-[#20211f] text-white":"hover:bg-[var(--surface-strong)]"}`}><span className="ch-mono w-7 text-[10px] opacity-50">{m.color==="w"?m.moveNumber+".":""}</span><span className="ch-mono flex-1">{m.san}</span><span className={`border px-1 py-0.5 text-[8px] font-bold ${tone(c)}`}>{(c||"GOOD").replace("INACCURACY","INAC").replace("BLUNDER","BLNDR")}</span></button>})}</div><div className="flex gap-1 border-t border-[var(--line)] p-3"><button onClick={()=>setIndex(-1)} className="ch-btn-secondary px-3 py-2 text-xs">|◀</button><button onClick={()=>setIndex(Math.max(-1,index-1))} className="ch-btn-secondary px-3 py-2 text-xs">◀</button><button onClick={()=>setIndex(Math.min(moves.length-1,index+1))} className="ch-btn-secondary px-3 py-2 text-xs">▶</button><button onClick={()=>setIndex(moves.length-1)} className="ch-btn-secondary px-3 py-2 text-xs">▶|</button></div></aside>
  <section className="order-1 flex min-w-0 flex-col xl:order-2"><div className="flex flex-1 items-center justify-center p-6 lg:p-10"><div className="relative w-full max-w-[560px]"><div className="absolute -left-7 top-0 h-full w-3 overflow-hidden border border-[var(--line)] bg-[#20211f]"><div className="absolute bottom-0 w-full bg-[#f0eee8]" style={{height:`${Math.max(5,Math.min(95,50+(after/max)*40))}%`}}/></div><div className="grid aspect-square grid-cols-8 border border-[var(--line)] shadow-[0_10px_30px_rgba(30,28,22,.12)]">{board.flatMap((row,r)=>row.map((piece,c)=>{const sq=files[c]+(8-r); const last=current&&[...new Chess().history({verbose:true})].length?false:false; return <div key={sq} className={`relative grid place-items-center ${(r+c)%2?"bg-[var(--board-dark)]":"bg-[var(--board-light)]"} ${current&&sq===current.san.slice(-2)?"ring-4 ring-inset ring-[color-mix(in_srgb,var(--accent)_35%,transparent)]":""}`}><span className={`relative z-10 text-[clamp(24px,5vw,54px)] leading-none ${piece?.color==="w"?"text-[#f8f6f0] [text-shadow:0_1px_1px_#555]":"text-[#1e1d1a]"}`}>{piece?glyph[piece.color+piece.type]:""}</span>{c===0&&<span className="absolute left-1 top-1 text-[8px] opacity-50">{8-r}</span>}{r===7&&<span className="absolute bottom-1 right-1 text-[8px] opacity-50">{files[c]}</span>}</div>}))}</div></div></div><div className="border-t border-[var(--line)] bg-[var(--surface-strong)] p-3"><div className="relative h-[74px] overflow-hidden"><svg viewBox="0 0 900 100" preserveAspectRatio="none" className="h-full w-full"><path d={`M0,50 ${evals.map((v,i)=>{const x=evals.length<2?0:i/(evals.length-1)*900;const y=50-Math.max(-max,Math.min(max,v))/max*38;return `L${x.toFixed(1)},${y.toFixed(1)}`}).join(" ")} L900,100 L0,100 Z`} fill="#565754" opacity=".75"/><line x1="0" x2="900" y1="50" y2="50" stroke="var(--line)"/></svg>{index>=0&&<span className="absolute top-0 h-full border-l-2 border-[var(--accent)]" style={{left:`${index/Math.max(1,moves.length-1)*100}%`}}/>}</div></div></section>
  <aside className="order-3 border-l border-[var(--line)] bg-[var(--surface-strong)]"><div className="flex justify-between border-b border-[var(--line)] px-5 py-4"><span className="ch-eyebrow text-[8px] text-[var(--muted)]">ANALYSIS</span><span className="ch-mono text-[9px] text-[var(--muted)]">Move {current?.moveNumber||"—"}</span></div><div className="divide-y divide-[var(--line)]"><div className="p-5"><div className="flex justify-between"><span className="ch-eyebrow text-[8px] text-[var(--muted)]">ENGINE</span><span className="ch-mono text-[9px] text-[var(--accent)]">∞ DEPTH 20</span></div><div className="ch-mono mt-4 text-[11px] leading-6 text-[var(--muted)]">{a?.principalVariation?.slice(0,6).join(" ")||"Select a move to inspect the engine line."}</div><div className={`mt-5 text-3xl font-black ${after<0?"text-[var(--danger)]":"text-[var(--accent)]"}`}>{a?.evaluationAfter==null?"—":formatEval(after)}</div></div><div className="p-5"><div className="ch-eyebrow text-[8px] text-[var(--muted)]">MOVE VERDICT</div><div className={`mt-3 text-xl font-black ${classification.includes("BLUNDER")?"text-[var(--danger)]":classification.includes("MISTAKE")?"text-[var(--warning)]":"text-[var(--accent)]"}`}>{classification}</div><p className="mt-3 text-[12px] leading-5 text-[var(--muted)]">{a?.evaluationLoss?`This move changed the position by ${a.evaluationLoss.toFixed(2)} evaluation points and gave the opponent clearer practical chances.`:"Engine analysis will describe the tactical and positional consequence here."}</p><div className="ch-mono mt-4 inline-flex border border-[var(--line)] px-2 py-1 text-[10px]"><span className="text-[var(--accent)]">{formatEval(before)}</span><span className="mx-2">→</span><span className="text-[var(--danger)]">{formatEval(after)}</span></div></div><div className="p-5"><div className="ch-eyebrow text-[8px] text-[var(--muted)]">BEST ALTERNATIVE</div><div className="ch-mono mt-3 text-sm font-bold text-[var(--accent)]">Instead: {a?.bestMove||"—"}</div><p className="mt-2 text-[12px] leading-5 text-[var(--muted)]">The best continuation preserves pressure while keeping the position structurally sound.</p></div><div className="p-5"><div className="border-l-2 border-[var(--warning)] bg-[var(--bg)] p-3"><div className="ch-eyebrow text-[8px] text-[var(--warning)]">PATTERN DETECTED</div><div className="mt-2 text-[10px] font-bold tracking-wide">TACTICAL OVERREACH</div><p className="mt-2 text-[11px] leading-5 text-[var(--muted)]">Attacking before the position is ready can turn initiative into unnecessary tactical risk.</p></div></div></div></aside>
 </div>
}
function formatEval(v:number){return `${v>=0?"+":""}${v.toFixed(1)}`}
