"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { fetchJson } from "@/lib/api/fetch-json";
import AppShell from "@/components/layout/AppShell";

const starter = `[Event "Casual Game"]\n[Site "Chess.com"]\n[Date "2026.01.01"]\n[White "White"]\n[Black "Black"]\n[Result "1-0"]\n[TimeControl "600+0"]\n\n1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 1-0`;

export default function AnalyzeGameClient(){
  const router=useRouter(); const [pgn,setPgn]=useState(starter); const [depth,setDepth]=useState(10); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  async function submit(){setBusy(true);setMessage(null);try{const created=await fetchJson<{gameId:string}>("/api/games/from-pgn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pgn})});setMessage("Game imported. Running Stockfish analysis…");await fetchJson(`/api/games/${encodeURIComponent(created.gameId)}/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({depth})});router.push(`/games/${encodeURIComponent(created.gameId)}`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to analyze this PGN.");}finally{setBusy(false);}}
  return <AppShell username="PGN" playerNav={null}><main className="ch-canvas min-h-[calc(100vh-56px)] px-4 py-7 sm:px-6 lg:px-10"><div className="mx-auto max-w-6xl"><div className="border-b border-[var(--line)] pb-6"><p className="ch-eyebrow">Single-game analyzer</p><h1 className="ch-title mt-2 text-4xl font-bold">Analyze a PGN, move by move.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Paste one game, validate it, run real Stockfish analysis and open the same Game Review surface used by imported player games.</p></div><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="ch-panel p-5"><div className="flex items-center justify-between"><label htmlFor="pgn" className="ch-eyebrow">PGN</label><span className="ch-mono text-[9px] text-[var(--muted)]">{pgn.length.toLocaleString()} chars</span></div><textarea id="pgn" value={pgn} onChange={e=>setPgn(e.target.value)} spellCheck={false} className="ch-mono mt-4 min-h-[520px] w-full resize-y border border-[var(--line)] bg-[var(--bg)] p-4 text-xs leading-6 text-[var(--ink)] outline-none focus:border-[var(--accent)]"/><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-[var(--muted)]">Invalid or move-less PGNs are rejected before they enter the database.</span><button type="button" onClick={submit} disabled={busy||!pgn.trim()} className="ch-btn-primary px-5 py-3 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-50">{busy?"Analyzing…":"Validate + Analyze →"}</button></div>{message&&<div className="mt-4 border border-[var(--line)] bg-[var(--surface)] p-3 text-sm text-[var(--muted)]">{message}</div>}</section><aside className="space-y-4"><div className="ch-panel p-5"><p className="ch-eyebrow">Analysis profile</p><div className="mt-4 grid gap-2">{([[8,"Quick"],[12,"Standard"],[16,"Deep"]] as const).map(([value,label])=><button key={value} type="button" onClick={()=>setDepth(value)} className={`flex items-center justify-between border px-3 py-3 text-left text-sm ${depth===value?"border-[var(--accent)] bg-[var(--accent-soft)]":"border-[var(--line)]"}`}><span>{label}</span><span className="ch-mono text-[10px] text-[var(--muted)]">depth {value}</span></button>)}</div><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Depth is bounded for deployment reliability. Every returned metric comes from the real engine.</p></div><div className="ch-panel p-5"><p className="ch-eyebrow">Pipeline</p><div className="mt-4 space-y-3 text-sm"><div>01 · Parse + validate</div><div>02 · Persist normalized moves</div><div>03 · Stockfish position analysis</div><div>04 · Classify + explain</div><div>05 · Interactive review</div></div></div></aside></div></div></main></AppShell>;
}
