import Link from "next/link";

export default function Home() {
  return <main className="ch-shell min-h-screen lg:flex">
    <aside className="hidden w-[196px] shrink-0 flex-col bg-[var(--sidebar)] text-[#aaa9a4] lg:flex"><div className="flex h-[106px] items-center gap-3 border-b border-[var(--sidebar-line)] px-5"><span className="text-lg text-[var(--accent)]">♞</span><span className="text-[11px] font-black tracking-[.22em] text-[#e4e2dc]">CHESSLYSIS</span></div><div className="px-5 pt-9 text-[8px] font-bold tracking-[.22em] text-[#666762]">ANALYSIS</div><Link href="/analyze" className="relative mt-3 flex items-center gap-3 bg-[#183127] px-5 py-3 text-[13px] text-white"><span className="absolute left-0 h-full w-[3px] bg-[var(--accent)]"/>▦ <span>Analyze Game</span><span className="ml-auto bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-bold">NEW</span></Link><div className="space-y-5 px-5 pt-7 text-[13px]"><span className="block">▰ &nbsp; My Analysis</span><span className="block">⌁ &nbsp; Insights</span><div className="pt-4 text-[8px] font-bold tracking-[.22em] text-[#666762]">IMPROVE</div><span className="block">♞ &nbsp; Training</span><span className="block">▤ &nbsp; Openings</span><span className="block">◎ &nbsp; Tactics</span></div><div className="mt-auto border-t border-[var(--sidebar-line)] p-5 text-[12px]"><div className="mb-4">⚙ &nbsp; Settings</div><div>?</div></div></aside>
    <section className="min-w-0 flex-1">
      <header className="flex h-[51px] items-center justify-between border-b border-[var(--line)] px-6 lg:px-8"><div className="ch-eyebrow text-[9px] text-[var(--muted)]">CHESSLYSIS <span className="mx-2">›</span> ANALYZE GAME</div><div className="flex gap-3"><Link href="/analyze" className="ch-btn-secondary px-3 py-1.5 text-[11px] font-semibold">↥ Import PGN</Link><Link href="/analyze" className="ch-btn-secondary hidden px-3 py-1.5 text-[11px] font-semibold sm:block">⌕ Paste URL</Link><span className="grid h-7 w-7 place-items-center bg-[var(--accent)] text-[9px] font-bold text-white">GK</span></div></header>
      <div className="ch-canvas relative min-h-[calc(100vh-51px)] overflow-hidden px-7 py-16 md:px-16 lg:px-[68px] lg:py-28">
        <div className="grid max-w-[1220px] gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
          <div className="relative z-10"><div className="mb-7 flex items-center gap-3"><span className="h-px w-5 bg-[var(--accent)]"/><span className="ch-eyebrow">CHESS INTELLIGENCE PLATFORM</span></div>
            <h1 className="ch-title max-w-[620px] text-[54px] font-black leading-[.92] md:text-[78px] xl:text-[82px]">YOUR GAMES<br/>TELL A STORY.<br/>LEARN TO<br/><span className="text-[var(--accent)]">READ IT.</span></h1>
            <p className="ch-muted mt-8 max-w-[550px] text-[16px] leading-7">Chesslysis transforms your chess games into a precise diagnostic report — revealing the decisions, patterns, and moments that shaped each result.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/analyze" className="ch-btn-primary px-6 py-4 text-[13px] font-bold">Analyze a Game →</Link><a href="#features" className="ch-btn-secondary px-6 py-4 text-[13px] font-bold">Explore Features</a></div>
            <div className="ch-mono mt-9 flex flex-wrap gap-5 text-[11px] text-[var(--muted)]"><span>24 Move Categories</span><span className="border-l border-[var(--line)] pl-5">Engine Depth 20+</span><span className="border-l border-[var(--line)] pl-5">Instant Analysis</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[570px] lg:translate-y-2">
            <div className="absolute -right-12 top-8 border border-[var(--line)] bg-[var(--surface)] px-4 py-3"><div className="ch-eyebrow text-[8px]">OPENING</div><div className="mt-1 text-xl font-bold">E97</div><div className="text-[10px] text-[var(--muted)]">King's Indian</div></div>
            <div className="grid aspect-square max-w-[430px] grid-cols-8 overflow-hidden border-[10px] border-[var(--surface-strong)] shadow-[0_16px_45px_rgba(35,31,24,.13)]">
              {Array.from({length:64},(_,i)=><div key={i} className={`relative ${(Math.floor(i/8)+i)%2===0?"bg-[var(--board-light)]":"bg-[var(--board-dark)]"}`}>{[6,12,21,29,36,45,52,59].includes(i)&&<span className="absolute inset-0 grid place-items-center text-[clamp(22px,4vw,40px)] text-[#222]">{[6,12,21,29,36,45,52,59].indexOf(i)%3===0?"♟":"♞"}</span>}</div>)}
            </div>
            <div className="absolute -left-3 top-[-12px] border border-[var(--accent)] bg-[var(--surface-strong)] px-3 py-2 shadow-sm"><div className="text-[12px] font-bold text-[var(--accent)]">♞ Nf6</div><div className="mt-1 text-[7px] font-bold tracking-[.18em] text-[var(--muted)]">BEST MOVE</div></div>
            <div className="absolute -bottom-2 -right-1 w-36 border border-[var(--line)] bg-[var(--surface-strong)] p-4 shadow-[5px_6px_0_rgba(25,26,23,.08)]"><div className="text-[34px] font-black text-[var(--accent)]">+1.4</div><div className="ch-eyebrow mt-1 text-[8px]">POSITION EVAL</div><div className="mt-1 text-[9px] text-[var(--muted)]">depth 22 · stockfish</div></div>
            <div className="absolute -bottom-2 left-0 w-40 bg-[#1d1e1c] p-4 text-white"><div className="ch-eyebrow text-[8px] text-[#8f918b]">MOVE QUALITY</div>{[["Best","12"],["Good","8"],["Inaccuracy","3"],["Blunder","1"]].map(([a,b])=><div key={a} className="mt-2 flex justify-between text-[10px]"><span className="text-[#aaa9a4]">{a}</span><span className={a==="Blunder"?"text-[#c96b61]":"text-[var(--accent)]"}>{b}</span></div>)}</div>
          </div>
        </div>
        <div id="features" className="absolute bottom-0 left-0 flex h-[58px] w-full items-center gap-9 overflow-hidden bg-[#1b1c1a] px-6 text-[9px] font-bold tracking-[.2em] text-[#8e908a] md:px-12"><span>CLASSIFICATION</span><i className="text-[var(--accent)]">•</i><span>OPENING ANALYSIS</span><i className="text-[var(--accent)]">•</i><span>EVALUATION GRAPH</span><i className="text-[var(--accent)]">•</i><span>CRITICAL MOMENTS</span><i className="text-[var(--accent)]">•</i><span>TRAINING RECOMMENDATIONS</span></div>
      </div>
    </section>
  </main>;
}
