"use client";
import { fetchJson } from "@/lib/api/fetch-json";
import { useCallback, useEffect, useState } from "react";
import AppShell from "@/components/layout/AppShell";
import { ErrorState, LoadingState, EmptyState } from "@/components/ui/AsyncState";

type Pattern = { theme: string; occurrences: number; gamesAffected: number; averageLoss: number; severity: number; examples: { gameId:string; san:string; ply:number; phase:string; loss:number }[] };
type Data = { username:string; gamesAnalyzed:number; summary:{ primaryWeakness:string; affectedGames:number; totalCriticalErrors:number }; patterns: Pattern[] };
const color = (severity:number) => severity >= 75 ? "bg-red-400" : severity >= 55 ? "bg-amber-400" : "bg-cyan-400";
export default function RecurringMistakesClient({ username }: { username:string }) {
 const [data,setData]=useState<Data|null>(null); const [error,setError]=useState<string|null>(null); const [expanded,setExpanded]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);try{setData(await fetchJson<Data>(`/api/players/${encodeURIComponent(username)}/mistakes`,{cache:"no-store"}))}catch(e){setError(e instanceof Error?e.message:"Could not load recurring mistakes")}},[username]);
 useEffect(()=>{load()},[load]);
 if(error) return <AppShell username={username}><ErrorState title="Could not load mistake patterns" message={error} onRetry={load}/></AppShell>;
 if(!data) return <AppShell username={username}><LoadingState title="Detecting recurring patterns across your games..."/></AppShell>;
 return <AppShell username={username}><main className="mx-auto max-w-[1500px] px-4 py-7 lg:px-8">
   <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-400">Phase 2.3 · Pattern Intelligence</p><h1 className="mt-2 text-3xl font-bold">Recurring Mistake Detection</h1><p className="mt-2 text-sm text-slate-400">Chesslysis groups critical errors into repeated, actionable weakness patterns.</p></div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 font-mono text-xs text-slate-400">{data.gamesAnalyzed} games analyzed</span></div>
   {data.patterns.length===0 ? <EmptyState title="No recurring pattern detected yet" message="Analyze more games to give the pattern engine enough evidence."/> : <>
   <section className="grid gap-4 md:grid-cols-3"><Metric label="Primary weakness" value={data.summary.primaryWeakness}/><Metric label="Games affected" value={`${data.summary.affectedGames}`} /><Metric label="Critical errors clustered" value={`${data.summary.totalCriticalErrors}`} /></section>
   <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Detected patterns</h2><p className="mt-1 text-xs text-slate-500">Ranked by frequency and average evaluation loss.</p></div><span className="text-xs text-cyan-300">Click a pattern to inspect</span></div><div className="space-y-3">{data.patterns.map(p=><button key={p.theme} onClick={()=>setExpanded(expanded===p.theme?null:p.theme)} className="w-full rounded-xl border border-white/10 bg-white/[.025] p-4 text-left transition hover:bg-white/[.05]"><div className="flex gap-4"><div className={`mt-1 h-2 w-2 rounded-full ${color(p.severity)}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{p.theme}</h3><span className="font-mono text-xs text-slate-400">Risk score {p.severity}/100</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${color(p.severity)}`} style={{width:`${p.severity}%`}}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-slate-500"><span>{p.occurrences} occurrences</span><span>{p.gamesAffected} games</span><span>{p.averageLoss.toFixed(2)} avg loss</span></div>{expanded===p.theme&&<div className="mt-4 border-t border-white/10 pt-3 text-sm text-slate-400"><p className="mb-2 text-xs uppercase tracking-wider text-slate-500">Example positions</p>{p.examples.map((x,i)=><div key={i} className="flex justify-between py-1"><span>{x.san} · {x.phase}</span><span className="font-mono text-red-300">−{x.loss.toFixed(2)}</span></div>)}</div>}</div></div></button>)}</div></div>
   <aside className="rounded-2xl border border-violet-400/20 bg-gradient-to-b from-violet-500/10 to-transparent p-5"><div className="flex items-center gap-2 text-violet-300"><span>✦</span><span className="text-xs font-semibold uppercase tracking-wider">Automatic Insight Engine</span></div><h2 className="mt-4 text-xl font-bold">Your biggest improvement opportunity</h2><p className="mt-3 leading-7 text-slate-400"><span className="font-semibold text-white">{data.summary.primaryWeakness}</span> appears repeatedly across independent games. This is more useful than a single-game blunder because the pattern persists.</p><div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Suggested next step</p><p className="mt-2 text-sm text-slate-300">Review the example positions, identify the decision trigger, then practice a focused drill before checking whether the pattern declines in your next games.</p></div></aside></section></>}
 </main></AppShell>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><div className="text-xs uppercase tracking-wider text-slate-500">{label}</div><div className="mt-3 text-2xl font-bold text-white">{value}</div></div>}
